spring:
  cloud:
    config:
      server:
        git:
# In production mode, it is recommended to configure external url link (github)         
#          uri: https://github.com/shahzadmasud/yap-config
# In development mode, it is recommended to configure local file-system
         uri: file:///Users/shahzadmasud/Documents/workspace/digitify/yap/yap-config
# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 8888          
